version: '3.1'

services:
  mysql:
    image: mysql:8.0.29
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: sakila
      TZ: 'Asia/Tokyo'
    volumes:
      - ./init:/docker-entrypoint-initdb.d
    ports:
      - '3306:3306'
